# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Sources:
# - https://bookdown.org/yihui/bookdown/github.html
# - https://bookdown.org/yihui/bookdown/build-the-book.html#build-the-book
# - https://github.com/rstudio/bookdown-demo

os: linux
language: r
cache: packages
pandoc_version: 1.19.2.1

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
