# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Sources:
# - https://bookdown.org/yihui/bookdown/github.html
# - https://bookdown.org/yihui/bookdown/build-the-book.html#build-the-book
# - https://github.com/rstudio/bookdown-demo

os: linux
language: r
cache: packages
pandoc_version: 1.19.2.1

env:
  global:
    secure: KLKHYPnjxlH4XS3DpnU2C8mCrLBzhvP3SfD0FNd+5L8joVzIuPpo+9+b9WdpoeMibQBBlPH2C56KDlB9niPN+5jba+CqcYTCoDFrzp1uGdiKzn93sCKKlqtaHqufvqym43xehiuV+AnBrbodamTBWbupw4gzvYTs78PWZWi69CcMyFp9DhH57b8qMhWPNbHpiMpRYEln4L86BP/PFs8jD+i4ORLvD8+UaQR0Fxv8cRaqGKfNXPnG2xsEj60P0OqfnvAWq2h749RIwb2vRel6XAa+AtjN2o2XJXGjcfrFfWM8/eFYnSdwKCSAZd/IW1AI/yTMnfIRGZIOMYXC3s20/Ov3C6RsQ1ynoxAnUxckwLqm8aRnGVtYPybL7y+tEfaBr4sT8if8pT/BTUBJD3tPZlZMZaBA9tvvXJOhL9EA/2c5oXHsWMF/IIisDVWbHsVk7iehDqca7gRtXP7gxWocq2YAtB9qGik3uws31qQzJX4+8dKCZLAY3qheLUDy+xxtpec59qNcuIWun4HIM4JmW2HTT5S1l2Jwa5OWOeN7Yaxx9luo795YWQw/qNgBOlJpkwC1GCocHB8qjay4c3h2ju0gwSKqkk1cjtGmR+aOuhv3I+dA+DAc4BlFwd0XnET3X+fzvxzAAHRFqIwoWUMvTC7I9/+eEB3FEWmo2sESXZc=

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
