# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Sources:
# - https://bookdown.org/yihui/bookdown/github.html
# - https://bookdown.org/yihui/bookdown/build-the-book.html#build-the-book
# - https://github.com/rstudio/bookdown-demo

os: linux
language: r
cache: packages
pandoc_version: 1.19.2.1

env:
  global:
    secure: ZvlxSDkf8rUHrRxhVWXH+YkcubFuOT3s18nzQcxDyzvmOV1kavhzBx6NnEyg/zoHaHujSEpdGUxAxzFLoQQ+sxxaPELyxOoESrxhfVgA0+DtgIQEb2FTxu9qgx9pmzxiMws2OrygDNz3c1ArOAnxF0BILVZW4URV0PnsYz9JimHaETSBxdRf2mCeSZYXONACAn3vUay3snHbAOlXfw4mQpeWP8vZsXbvSRygWHrpJERl7SFsiO62m25ZjPrTtD0IKGDDNP0pcoQccR+iWl45rFsCUo1q06arDMU8hr1AolR+lrsVX1cNOcrB/c0SPYZ22Ps0Q5w9Wf51Z8miQxFZGO4p+g8TjpwRDubRfn9EutZf2BZ6noNql94i+DAsX3Sor5AEK+aWFQgP0itJ1dbA/w4gj9gEbQjOptdsAZhPKh/ywQTHY3xsmo7GALdJ0jlTQWgHVw9k+SgtPQp0ziLp3UaDiVqEiZSsXAnrN/KXCf7DH1kwv4cwkNg0ioTK2oj5pxxNR2Hwf1djzTObl6bQzq2tNyMKGRji9QorgwJc6tG/Tcz0f1LsJIAyeY7xul6Yeg7oOsujIePc/kINOBa4eetF4+x8hVAEZNvG0aw5aQmRYjTfzLmHsMPLrKhZL4bO8ITAuA2ZW7lXYLudqTIL08zPNoes/X9RemdDfOm9rwo=

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
